- name: Install redis
  become: yes
  apt:
    name: redis-server
    update_cache: yes

- name: Copy redis.conf file
  become: yes
  copy:
    src: roles/redis/files/redis.conf
    dest: /etc/redis/redis.conf   

- name: Restart redis
  become: yes
  service:
    name: redis
    state: restarted
    enabled: yes